# Generated by Django 5.1.4 on 2024-12-16 12:38

import album.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.TextField(default=album.models.create_default_signature)),
                ('seed', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(choices=[('IDLE', 'IDLE'), ('ENQUEUED', 'ENQUEUED'), ('RUNNING', 'RUNNING'), ('FINISHED', 'FINISHED')], default='IDLE')),
                ('error', models.TextField()),
                ('request_by', models.TextField(null=True, validators=[django.core.validators.EmailValidator()])),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('signature',), name='unique_signature'), models.UniqueConstraint(fields=('seed',), name='unique_seed')],
            },
        ),
    ]
