# Generated by Django 5.1.4 on 2024-12-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='error',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='status',
            field=models.TextField(choices=[('IDLE', 'IDLE'), ('RUNNING', 'RUNNING'), ('FINISHED', 'FINISHED')], default='IDLE'),
        ),
    ]
