name: "deploy-cddn24-backend-worker"
on:
  push:
    branches:
      - production
      - staging
    paths:
      - 'cddn24/**/*'
  workflow_dispatch:
jobs:
  deploy-cddn24:
    runs-on: ubuntu-latest
    steps:
      
      - name: Set the version for staging
        id: set_image_version_staging
        if: ${{ github.ref == 'refs/heads/staging' }}
        run: echo "image-version=staging" >> $GITHUB_ENV

      - name: Set the version for production
        id: set_image_version_production
        if: ${{ github.ref == 'refs/heads/production' }}
        run: echo "image-version=latest" >> $GITHUB_ENV
      

      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: willywongi
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      -
        name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: willywongi/cd-di-natale-24:${{ env.image-version  }}
          context: ./cddn24
          target: backend
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: GIT_SHA=${{ github.sha }}

      -
        name: Build and push worker
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: willywongi/cd-di-natale-24-worker:${{ env.image-version  }}
          context: ./cddn24
          target: worker
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: GIT_SHA=${{ github.sha }}
